---
- name: Install Required Packages
  hosts: web
  become: yes
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - curl
        - git
